find_library(SDL2_LIBRARY
    NAMES SDL2
    PATHS "${CMAKE_CURRENT_LIST_DIR}/${PLATFORM_PREFIX}/lib" "${CMAKE_CURRENT_LIST_DIR}/${PLATFORM_PREFIX}"
    NO_DEFAULT_PATH
)
find_path(SDL2_INCLUDE_DIR
    NAMES SDL.h
    PATHS "${CMAKE_CURRENT_LIST_DIR}/include"
    PATH_SUFFIXES SDL2
    NO_DEFAULT_PATH
)
set(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
set(SDL2_LIBRARIES ${SDL2_LIBRARY})

mark_as_advanced(SDL2_INCLUDE_DIR SDL2_LIBRARY)
